openapi: "3.0.0"
info:
  version: 1.0.0
  title: Prices API
  description: A sample API for prices fetching
  
paths:
  /prices:
    get:
      summary: get price
      operationId: get price
      tags:
        - price
      parameters:
        - in: query
          name: productId
          schema:
            type: integer
            format: int64
          required: true
          description: id of the product
        - in: query
          name: brandId
          schema:
            type: integer
            format: int64
          required: true
          description: id of the brand
        - in: query
          name: startDate
          schema:
            type: string
            format: date-time
          required: true
          description: start date for the price to apply
      responses:
        200:
          description: the price that applies
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/price"
        204:
          description: no price found
        default:
          description: unknown error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
          
components:
  schemas:
    price:
      type: object
      properties:
        productId:
         type: integer
         format: int64
         example: 457823
        brandId:
          type: integer
          format: int64
          example: 1
        rateId:
          type: integer
          format: int64
          example: 1
        price:
          type: number
          format: double
          example: 305.67
        startDate:
          type: string
          format: date-time
          example: 2020-06-14T00:00:00Z
        endDate:
          type: string
          format: date-time
          example: 2020-06-14T00:00:00Z
    error:
      type: object
      properties:
        code:
          type: integer
          format: int64
          example: 1000
        message:
          type: string
          example: unknown error occurred contact support
 