CREATE TABLE IF NOT EXISTS `PRICES` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `BRAND_ID` INT NOT NULL,
  `START_DATE` TIMESTAMP NOT NULL,
  `END_DATE` TIMESTAMP NOT NULL,
  `PRICE_LIST` INT NOT NULL,
  `PRODUCT_ID` INT NOT NULL,
  `PRIORITY` INT NOT NULL,
  `PRICE` FLOAT NOT NULL,
  `CURRENCY` VARCHAR(5) NOT NULL
);
