spring:
  h2:
    console.enabled: true
  jpa:
    database: H2
    generate-ddl: false
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:prices
    username: testuser
    password: testpassword
  flyway:
    locations:
    - classpath:db/migration
    user: testuser
    password: testpassword
    schemas:
    - prices
    url: jdbc:h2:mem:prices

  
    
   